// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>


///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Frame;
lv_obj_t *ui_FrameButtom;
lv_obj_t *ui_SettingButton;
lv_obj_t *ui_Getting_data_text;
lv_obj_t *ui_Time;
lv_obj_t *ui_Date;
lv_obj_t *ui_Day;
lv_obj_t *ui_WeatherMain;
lv_obj_t *ui_Temperature;
lv_obj_t *ui_Cityname;

int get_weather(char *city_input);
void show_time_and_weather();


//SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
lv_obj_t *input_city_area;
lv_obj_t *ui_Getting_data_text;
// extern lv_obj_t *pinyin_ime;
lv_obj_t *cand_panel; // static panel for pinyin input

// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);

// sync system time with ntp server
setenv("TZ", "Asia/Shanghai", 1);
tzset();

const char *syncTime_cmd = "busybox ntpd -n -q -p ntp.aliyun.com";
int syncTime_ret = system(syncTime_cmd);
if (syncTime_ret == -1) {
    perror("system");
    return;
}

printf("sync time with ntp server: %d\n", syncTime_ret);


// init screen 1
ui_Screen1_screen_init();

// fill weather data with default city
printf("ui_init: Initializing weather data for default city...\n");
char *default_city = "Guangzhou";
while (get_weather(default_city)){  // while 1 if error
    printf("ui_init: Error getting weather data for default city '%s'. Retrying...\n", default_city);
    sleep(1);
}
printf("ui_init: Weather data initialized successfully.");
show_time_and_weather();    // "render" time and weather to screen


ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
printf("ui_init: Exiting ui_init function.\n");
}
