// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Frame;
extern lv_obj_t *ui_FrameButtom;
extern lv_obj_t *ui_SettingButton;
extern lv_obj_t *ui_Getting_data_text;
extern lv_obj_t *ui_Time;
extern lv_obj_t *ui_Date;
extern lv_obj_t *ui_Day;
extern lv_obj_t *ui_WeatherMain;
extern lv_obj_t *ui_Temperature;
extern lv_obj_t *ui_Cityname;

//SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *input_city_area;
extern lv_obj_t *ui_Getting_data_text;
// extern lv_obj_t *pinyin_ime;
extern lv_obj_t *cand_panel; // static panel for pinyin input

// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_NanoDyongSong_40);
LV_FONT_DECLARE( ui_font_NanoDyongSong_60);
LV_FONT_DECLARE( ui_font_DroidSansFallback_40);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
