// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

#include <stdio.h>
#include <time.h>
#include <stdlib.h>

// date time etc global
char DATE_STR[6]; // MM/DD format
char DAY_STR[4]; // Day format
char TIME_STR[6]; // HH:MM format
char *CITY_NAME = NULL;
char *WEATHER_MAIN = NULL;
char *TEMPERATURE = NULL;
char *ADVICE = NULL;

lv_style_t AI_recommendation_style;

// for test: button click print msg
/*
static void btn_on_click_test(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        printf("Button clicked!\n");
    }
}
*/

static void go_to_screen2()
{
    printf("go_to_screen2: Switching to Screen2...\n");
    ui_Screen2_screen_init();
    lv_scr_load(ui_Screen2);
}

static void button_on_click(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_CLICKED) {
        printf("button_on_click: Button clicked.\n");
        go_to_screen2();
    }
}

int get_weather(char *city_input)
{
    printf("get_weather: Fetching weather data...\n");
    char cmd[512] = {0};
    // run ./GetWeather <city_name> command
    snprintf(cmd, 256, "./GetWeather %s", city_input);
    char weather_data[512] = {0};
    FILE *fp = popen(cmd, "r");
    if (fp == NULL) {
        perror("get_weather: Failed to run command");
        return 1;
    }
    fgets(weather_data, sizeof(weather_data), fp);
    pclose(fp);
    if (strlen(weather_data) == 0) {
        printf("get_weather: Error: No weather data received.\n");
        return 1;
    }
    // separate output by ,
    printf("get_weather: Weather data raw: %s\n", weather_data);
    // use strdup because strtok is a pointer inside the function and will be freed after the function returns
    CITY_NAME = strdup(strtok(weather_data, ","));
    strtok(NULL, ","); // skip lat
    strtok(NULL, ","); // skip lon
    WEATHER_MAIN = strdup(strtok(NULL, ","));
    TEMPERATURE = strdup(strtok(NULL, ","));
    ADVICE = strdup(strtok(NULL, ","));
    if (CITY_NAME == NULL || WEATHER_MAIN == NULL || TEMPERATURE == NULL || ADVICE == NULL) {
        printf("get_weather: Error: Failed to parse weather data.\n");
        return 1;
    }
    printf("get_weather: Get weather data successfully.\n");
    return 0; // success
}

static void update_time(lv_timer_t *timer) {
    time_t t = time(NULL);
    struct tm *tm_info = localtime(&t);
    strftime(TIME_STR, sizeof(TIME_STR), "%H:%M", tm_info);
    lv_label_set_text(ui_Time, TIME_STR);
}

void show_time_and_weather()
{
printf("show_time_and_weather: Syncing system date and time...\n");
// sync system date and time
time_t t = time(NULL);
struct tm *tm_info = localtime(&t);

// date string
strftime(DATE_STR, sizeof(DATE_STR), "%m/%d", tm_info);

// day string
strftime(DAY_STR, sizeof(DAY_STR), "%a", tm_info);

// time string
strftime(TIME_STR, sizeof(TIME_STR), "%H:%M", tm_info);

printf("show_time_and_weather: Sending time and weather data to UI...\n");
lv_label_set_text(ui_Date, DATE_STR);
printf("show_time_and_weather: DATE_STR = %s\n", DATE_STR);
lv_label_set_text(ui_Day, DAY_STR);
printf("show_time_and_weather: DAY_STR = %s\n", DAY_STR);
lv_label_set_text(ui_Time, TIME_STR);
printf("show_time_and_weather: TIME_STR = %s\n", TIME_STR);
lv_label_set_text(ui_Cityname, CITY_NAME);
printf("show_time_and_weather: CITY_NAME = %s\n", CITY_NAME);
lv_label_set_text(ui_WeatherMain, WEATHER_MAIN); 
printf("show_time_and_weather: WEATHER_MAIN = %s\n", WEATHER_MAIN);
lv_label_set_text(ui_Temperature, TEMPERATURE);
printf("show_time_and_weather: TEMPERATURE = %s\n", TEMPERATURE);
lv_label_set_text(ui_Getting_data_text, ADVICE);
printf("show_time_and_weather: ADVICE = %s\n", ADVICE);
}

void fontInit(){
    static lv_ft_info_t info;
    info.name = "NanoDyongSong.ttf";
    info.weight = 30;
    info.style = FT_FONT_STYLE_NORMAL;
    info.mem = NULL;
    if(!lv_ft_font_init(&info)) {
        LV_LOG_ERROR("fontInit: create failed.");
    }

    /*Create style with the new font*/
    lv_style_init(&AI_recommendation_style);
    lv_style_set_text_font(&AI_recommendation_style, info.font);
    lv_style_set_text_align(&AI_recommendation_style, LV_TEXT_ALIGN_LEFT);
}

void ui_Screen1_screen_init(void)
{
printf("ui_Screen1_screen_init: Initializing fonts...\n");
fontInit();

printf("ui_Screen1_screen_init: Start initializing UI Screen1...\n");
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x89A68A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

printf("ui_Screen1_screen_init: Initializing ui_Frame...\n");
ui_Frame = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Frame);
lv_obj_set_width( ui_Frame, 800);
lv_obj_set_height( ui_Frame, 484);
lv_obj_set_align( ui_Frame, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Frame, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Frame, lv_color_hex(0x635B51), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Frame, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Frame, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

printf("ui_Screen1_screen_init: Initializing ui_FrameButtom...\n");
ui_FrameButtom = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_FrameButtom);
lv_obj_set_width( ui_FrameButtom, 803);
lv_obj_set_height( ui_FrameButtom, 50);
lv_obj_set_x( ui_FrameButtom, 0 );
lv_obj_set_y( ui_FrameButtom, 199 );
lv_obj_set_align( ui_FrameButtom, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FrameButtom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_FrameButtom, lv_color_hex(0x645D52), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FrameButtom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

printf("ui_Screen1_screen_init: Initializing ui_AIRecommendation...\n");
ui_Getting_data_text = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Getting_data_text, 400);  /// 1
lv_obj_set_height( ui_Getting_data_text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Getting_data_text, 45 );
lv_obj_set_y( ui_Getting_data_text, 190 );
lv_label_set_long_mode(ui_Getting_data_text, LV_LABEL_LONG_WRAP);
lv_label_set_text(ui_Getting_data_text,"Recommendation Text");
lv_obj_set_style_text_color(ui_Getting_data_text, lv_color_hex(0x44434D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Getting_data_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_text_font(ui_Getting_data_text, &ui_font_NanoDyongSong_40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_add_style(ui_Getting_data_text, &AI_recommendation_style, LV_PART_MAIN | LV_STATE_DEFAULT);

printf("ui_Screen1_screen_init: Initializing ui_Time...\n");
ui_Time = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Time, 45 );
lv_obj_set_y( ui_Time, 45 );
lv_label_set_text(ui_Time,"00:00");
lv_obj_set_style_text_color(ui_Time, lv_color_hex(0x44434D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Time, &ui_font_NanoDyongSong_60, LV_PART_MAIN| LV_STATE_DEFAULT);

printf("ui_Screen1_screen_init: Initializing ui_Date...\n");
ui_Date = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Date, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Date, 292 );
lv_obj_set_y( ui_Date, 45 );
lv_label_set_text(ui_Date,"MM/DD");
lv_obj_set_style_text_color(ui_Date, lv_color_hex(0x44434D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Date, &ui_font_NanoDyongSong_60, LV_PART_MAIN| LV_STATE_DEFAULT);

printf("ui_Screen1_screen_init: Initializing ui_Day...\n");
ui_Day = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Day, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Day, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Day, 562 );
lv_obj_set_y( ui_Day, 45 );
lv_label_set_text(ui_Day,"Day");
lv_obj_set_style_text_color(ui_Day, lv_color_hex(0x44434D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Day, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Day, &ui_font_NanoDyongSong_60, LV_PART_MAIN| LV_STATE_DEFAULT);

printf("ui_Screen1_screen_init: Initializing ui_WeatherMain...\n");
ui_WeatherMain = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_WeatherMain, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherMain, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherMain, 495 );
lv_obj_set_y( ui_WeatherMain, 140 );
lv_label_set_text(ui_WeatherMain,"Weather Main");
lv_obj_set_style_text_color(ui_WeatherMain, lv_color_hex(0x44434D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WeatherMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WeatherMain, &ui_font_NanoDyongSong_40, LV_PART_MAIN| LV_STATE_DEFAULT);

printf("ui_Screen1_screen_init: Initializing ui_Temperature...\n");
ui_Temperature = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Temperature, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature, 495 );
lv_obj_set_y( ui_Temperature, 190 );
lv_label_set_text(ui_Temperature,"Temperature");
lv_obj_set_style_text_color(ui_Temperature, lv_color_hex(0x44434D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Temperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temperature, &ui_font_NanoDyongSong_40, LV_PART_MAIN| LV_STATE_DEFAULT);

printf("ui_Screen1_screen_init: Initializing ui_Cityname...\n");
ui_Cityname = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Cityname, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Cityname, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Cityname, 45 );
lv_obj_set_y( ui_Cityname, 140 );
lv_label_set_text(ui_Cityname,"CityName");
lv_obj_set_style_text_color(ui_Cityname, lv_color_hex(0x44434D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Cityname, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Cityname, &ui_font_NanoDyongSong_40, LV_PART_MAIN| LV_STATE_DEFAULT);

printf("ui_Screen1_screen_init: Initializing ui_SettingButton...\n");
ui_SettingButton = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_SettingButton, 82);
lv_obj_set_height( ui_SettingButton, 17);
lv_obj_set_x( ui_SettingButton, 338 );
lv_obj_set_y( ui_SettingButton, 208 );
lv_obj_set_align( ui_SettingButton, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SettingButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SettingButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SettingButton, lv_color_hex(0xC1EDD5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_flag(ui_SettingButton, LV_OBJ_FLAG_CLICKABLE);
lv_obj_move_foreground(ui_SettingButton);

// update time every second
lv_timer_create(update_time, 1000, NULL);

show_time_and_weather(); // show current time and temporary stored weather data

// below: event handling
printf("ui_Screen1_screen_init: Setting up event handling...\n");
// handle button click events
lv_obj_add_event_cb(ui_SettingButton, button_on_click, LV_EVENT_ALL, NULL);

printf("ui_Screen1_screen_init: UI Screen1 initialized.\n");
}
